# Generated by Django 4.0 on 2021-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_item', models.CharField(max_length=100)),
                ('is_Active', models.BooleanField(default=True)),
                ('is_Done', models.BooleanField(default=False)),
            ],
        ),
    ]
