# Generated by Django 4.0 on 2021-12-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_Active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_Done',
            new_name='is_done',
        ),
    ]
